// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ClusterLocationCoordinates struct {
	Latitude  *string `json:"latitude,omitempty"`
	Longitude *string `json:"longitude,omitempty"`
}

func (o *ClusterLocationCoordinates) GetLatitude() *string {
	if o == nil {
		return nil
	}
	return o.Latitude
}

func (o *ClusterLocationCoordinates) GetLongitude() *string {
	if o == nil {
		return nil
	}
	return o.Longitude
}
