// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CommonClusterCKPProviderType string

const (
	CommonClusterCKPProviderTypeBringYourOwnHost CommonClusterCKPProviderType = "BringYourOwnHost"
	CommonClusterCKPProviderTypeAws              CommonClusterCKPProviderType = "AWS"
)

func (e CommonClusterCKPProviderType) ToPointer() *CommonClusterCKPProviderType {
	return &e
}

func (e *CommonClusterCKPProviderType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "BringYourOwnHost":
		fallthrough
	case "AWS":
		*e = CommonClusterCKPProviderType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CommonClusterCKPProviderType: %v", v)
	}
}
