// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonProxyInfo struct {
	HTTP    *string `json:"http,omitempty"`
	HTTPS   *string `json:"https,omitempty"`
	NoProxy *string `json:"noProxy,omitempty"`
}

func (o *CommonProxyInfo) GetHTTP() *string {
	if o == nil {
		return nil
	}
	return o.HTTP
}

func (o *CommonProxyInfo) GetHTTPS() *string {
	if o == nil {
		return nil
	}
	return o.HTTPS
}

func (o *CommonProxyInfo) GetNoProxy() *string {
	if o == nil {
		return nil
	}
	return o.NoProxy
}
