// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonClusterEKSInfo struct {
	Provider   *string                        `json:"provider,omitempty"`
	Region     *string                        `json:"region,omitempty"`
	K8sVersion *string                        `json:"k8sVersion,omitempty"`
	NodeInfo   *CommonClusterEKSNodeGroupInfo `json:"nodeInfo,omitempty"`
}

func (o *CommonClusterEKSInfo) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *CommonClusterEKSInfo) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *CommonClusterEKSInfo) GetK8sVersion() *string {
	if o == nil {
		return nil
	}
	return o.K8sVersion
}

func (o *CommonClusterEKSInfo) GetNodeInfo() *CommonClusterEKSNodeGroupInfo {
	if o == nil {
		return nil
	}
	return o.NodeInfo
}
