// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonClusterAKSNodeInfo struct {
	SysNodeInfo  *CommonClusterAKSSysNodeGroupInfo  `json:"sysNodeInfo,omitempty"`
	UserNodeInfo *CommonClusterAKSUserNodeGroupInfo `json:"userNodeInfo,omitempty"`
}

func (o *CommonClusterAKSNodeInfo) GetSysNodeInfo() *CommonClusterAKSSysNodeGroupInfo {
	if o == nil {
		return nil
	}
	return o.SysNodeInfo
}

func (o *CommonClusterAKSNodeInfo) GetUserNodeInfo() *CommonClusterAKSUserNodeGroupInfo {
	if o == nil {
		return nil
	}
	return o.UserNodeInfo
}
