// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonClusterKubeInfo struct {
	K8sName     *string `json:"k8sName,omitempty"`
	K8sVersion  *string `json:"k8sVersion,omitempty"`
	CniName     *string `json:"cniName,omitempty"`
	CniVersion  *string `json:"cniVersion,omitempty"`
	VirtualIP   *string `json:"virtualIP,omitempty"`
	MasterNodes *int    `json:"masterNodes,omitempty"`
	WorkerNodes *int    `json:"workerNodes,omitempty"`
}

func (o *CommonClusterKubeInfo) GetK8sName() *string {
	if o == nil {
		return nil
	}
	return o.K8sName
}

func (o *CommonClusterKubeInfo) GetK8sVersion() *string {
	if o == nil {
		return nil
	}
	return o.K8sVersion
}

func (o *CommonClusterKubeInfo) GetCniName() *string {
	if o == nil {
		return nil
	}
	return o.CniName
}

func (o *CommonClusterKubeInfo) GetCniVersion() *string {
	if o == nil {
		return nil
	}
	return o.CniVersion
}

func (o *CommonClusterKubeInfo) GetVirtualIP() *string {
	if o == nil {
		return nil
	}
	return o.VirtualIP
}

func (o *CommonClusterKubeInfo) GetMasterNodes() *int {
	if o == nil {
		return nil
	}
	return o.MasterNodes
}

func (o *CommonClusterKubeInfo) GetWorkerNodes() *int {
	if o == nil {
		return nil
	}
	return o.WorkerNodes
}
