// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonClusterEKSNodeGroupInfo struct {
	InstanceType *string `json:"instanceType,omitempty"`
	Desired      *int    `json:"desired,omitempty"`
	Min          *int    `json:"min,omitempty"`
	Max          *int    `json:"max,omitempty"`
	AmiType      *string `json:"amiType,omitempty"`
}

func (o *CommonClusterEKSNodeGroupInfo) GetInstanceType() *string {
	if o == nil {
		return nil
	}
	return o.InstanceType
}

func (o *CommonClusterEKSNodeGroupInfo) GetDesired() *int {
	if o == nil {
		return nil
	}
	return o.Desired
}

func (o *CommonClusterEKSNodeGroupInfo) GetMin() *int {
	if o == nil {
		return nil
	}
	return o.Min
}

func (o *CommonClusterEKSNodeGroupInfo) GetMax() *int {
	if o == nil {
		return nil
	}
	return o.Max
}

func (o *CommonClusterEKSNodeGroupInfo) GetAmiType() *string {
	if o == nil {
		return nil
	}
	return o.AmiType
}
