// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonClusterAKSSysNodeGroupInfo struct {
	Desired  *int    `json:"desired,omitempty"`
	Min      *int    `json:"min,omitempty"`
	Max      *int    `json:"max,omitempty"`
	NodeSize *string `json:"nodeSize,omitempty"`
}

func (o *CommonClusterAKSSysNodeGroupInfo) GetDesired() *int {
	if o == nil {
		return nil
	}
	return o.Desired
}

func (o *CommonClusterAKSSysNodeGroupInfo) GetMin() *int {
	if o == nil {
		return nil
	}
	return o.Min
}

func (o *CommonClusterAKSSysNodeGroupInfo) GetMax() *int {
	if o == nil {
		return nil
	}
	return o.Max
}

func (o *CommonClusterAKSSysNodeGroupInfo) GetNodeSize() *string {
	if o == nil {
		return nil
	}
	return o.NodeSize
}
