// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonClusterGKEInfo struct {
	Provider     *string                       `json:"provider,omitempty"`
	Zone         *string                       `json:"zone,omitempty"`
	K8sVersion   *string                       `json:"k8sVersion,omitempty"`
	NodePoolInfo *CommonClusterGKENodePoolInfo `json:"nodePoolInfo,omitempty"`
}

func (o *CommonClusterGKEInfo) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *CommonClusterGKEInfo) GetZone() *string {
	if o == nil {
		return nil
	}
	return o.Zone
}

func (o *CommonClusterGKEInfo) GetK8sVersion() *string {
	if o == nil {
		return nil
	}
	return o.K8sVersion
}

func (o *CommonClusterGKEInfo) GetNodePoolInfo() *CommonClusterGKENodePoolInfo {
	if o == nil {
		return nil
	}
	return o.NodePoolInfo
}
