// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonByohProvider struct {
	MasterHostGroup *string `json:"masterHostGroup,omitempty"`
	VirtualIP       *string `json:"virtualIP,omitempty"`
	WorkerHostGroup *string `json:"workerHostGroup,omitempty"`
}

func (o *CommonByohProvider) GetMasterHostGroup() *string {
	if o == nil {
		return nil
	}
	return o.MasterHostGroup
}

func (o *CommonByohProvider) GetVirtualIP() *string {
	if o == nil {
		return nil
	}
	return o.VirtualIP
}

func (o *CommonByohProvider) GetWorkerHostGroup() *string {
	if o == nil {
		return nil
	}
	return o.WorkerHostGroup
}
