// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CommonClusterGKENodePoolInfo struct {
	MachineType      *string `json:"machineType,omitempty"`
	DiskSize         *int    `json:"diskSize,omitempty"`
	ImageType        *string `json:"imageType,omitempty"`
	InitialNodeCount *int    `json:"initialNodeCount,omitempty"`
	MinNodeCount     *int    `json:"minNodeCount,omitempty"`
	MaxNodeCount     *int    `json:"maxNodeCount,omitempty"`
}

func (o *CommonClusterGKENodePoolInfo) GetMachineType() *string {
	if o == nil {
		return nil
	}
	return o.MachineType
}

func (o *CommonClusterGKENodePoolInfo) GetDiskSize() *int {
	if o == nil {
		return nil
	}
	return o.DiskSize
}

func (o *CommonClusterGKENodePoolInfo) GetImageType() *string {
	if o == nil {
		return nil
	}
	return o.ImageType
}

func (o *CommonClusterGKENodePoolInfo) GetInitialNodeCount() *int {
	if o == nil {
		return nil
	}
	return o.InitialNodeCount
}

func (o *CommonClusterGKENodePoolInfo) GetMinNodeCount() *int {
	if o == nil {
		return nil
	}
	return o.MinNodeCount
}

func (o *CommonClusterGKENodePoolInfo) GetMaxNodeCount() *int {
	if o == nil {
		return nil
	}
	return o.MaxNodeCount
}
