// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ConfigClusterStatus struct {
	Cluster *ConfigCluster        `json:"cluster,omitempty"`
	Metrics *ConfigClusterMetrics `json:"metrics,omitempty"`
	State   *string               `json:"state,omitempty"`
}

func (o *ConfigClusterStatus) GetCluster() *ConfigCluster {
	if o == nil {
		return nil
	}
	return o.Cluster
}

func (o *ConfigClusterStatus) GetMetrics() *ConfigClusterMetrics {
	if o == nil {
		return nil
	}
	return o.Metrics
}

func (o *ConfigClusterStatus) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}
