// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ConfigClusterLocationRespGeolocation struct {
	ZipCode *string `json:"zipCode,omitempty"`
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
}

func (o *ConfigClusterLocationRespGeolocation) GetZipCode() *string {
	if o == nil {
		return nil
	}
	return o.ZipCode
}

func (o *ConfigClusterLocationRespGeolocation) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *ConfigClusterLocationRespGeolocation) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}
