// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ConfigClusterKey struct {
	Domain  *string `json:"domain,omitempty"`
	Project *string `json:"project,omitempty"`
	Cluster *string `json:"cluster,omitempty"`
}

func (o *ConfigClusterKey) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *ConfigClusterKey) GetProject() *string {
	if o == nil {
		return nil
	}
	return o.Project
}

func (o *ConfigClusterKey) GetCluster() *string {
	if o == nil {
		return nil
	}
	return o.Cluster
}
