// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ConfigPodStatus struct {
	Failed    *int `json:"failed,omitempty"`
	Succeeded *int `json:"succeeded,omitempty"`
	Pending   *int `json:"pending,omitempty"`
	Running   *int `json:"running,omitempty"`
	Capacity  *int `json:"capacity,omitempty"`
}

func (o *ConfigPodStatus) GetFailed() *int {
	if o == nil {
		return nil
	}
	return o.Failed
}

func (o *ConfigPodStatus) GetSucceeded() *int {
	if o == nil {
		return nil
	}
	return o.Succeeded
}

func (o *ConfigPodStatus) GetPending() *int {
	if o == nil {
		return nil
	}
	return o.Pending
}

func (o *ConfigPodStatus) GetRunning() *int {
	if o == nil {
		return nil
	}
	return o.Running
}

func (o *ConfigPodStatus) GetCapacity() *int {
	if o == nil {
		return nil
	}
	return o.Capacity
}
