// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ConfigTimeZone struct {
	Offset *int    `json:"offset,omitempty"`
	Zone   *string `json:"zone,omitempty"`
}

func (o *ConfigTimeZone) GetOffset() *int {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ConfigTimeZone) GetZone() *string {
	if o == nil {
		return nil
	}
	return o.Zone
}
