// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/himanshusahu0001/openapi/internal/utils"
)

type ConfigClusterLocationResp struct {
	// - NOT_CONFIGURED: not configured location type
	//  - COORDINATES: coordinates: latitude & longitude info
	//  - GEOLOCATION: geolocation: zip code & country info
	LocationType *ConfigClusterLocationType            `default:"NOT_CONFIGURED" json:"locationType"`
	Coordinates  *ClusterLocationCoordinates           `json:"coordinates,omitempty"`
	Geolocation  *ConfigClusterLocationRespGeolocation `json:"geolocation,omitempty"`
}

func (c ConfigClusterLocationResp) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigClusterLocationResp) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ConfigClusterLocationResp) GetLocationType() *ConfigClusterLocationType {
	if o == nil {
		return nil
	}
	return o.LocationType
}

func (o *ConfigClusterLocationResp) GetCoordinates() *ClusterLocationCoordinates {
	if o == nil {
		return nil
	}
	return o.Coordinates
}

func (o *ConfigClusterLocationResp) GetGeolocation() *ConfigClusterLocationRespGeolocation {
	if o == nil {
		return nil
	}
	return o.Geolocation
}
