// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ConfigNodeStatus struct {
	Ready *int `json:"ready,omitempty"`
	Total *int `json:"total,omitempty"`
}

func (o *ConfigNodeStatus) GetReady() *int {
	if o == nil {
		return nil
	}
	return o.Ready
}

func (o *ConfigNodeStatus) GetTotal() *int {
	if o == nil {
		return nil
	}
	return o.Total
}
