// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ConfigClusterAppInstanceInfo struct {
	ManagedInstanceCount *int `json:"managedInstanceCount,omitempty"`
}

func (o *ConfigClusterAppInstanceInfo) GetManagedInstanceCount() *int {
	if o == nil {
		return nil
	}
	return o.ManagedInstanceCount
}
