// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ConfigResourceUsageMetrics struct {
	Usage    *float64 `json:"usage,omitempty"`
	Capacity *float64 `json:"capacity,omitempty"`
}

func (o *ConfigResourceUsageMetrics) GetUsage() *float64 {
	if o == nil {
		return nil
	}
	return o.Usage
}

func (o *ConfigResourceUsageMetrics) GetCapacity() *float64 {
	if o == nil {
		return nil
	}
	return o.Capacity
}
