// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ConfigClusterLocationType - - NOT_CONFIGURED: not configured location type
//   - COORDINATES: coordinates: latitude & longitude info
//   - GEOLOCATION: geolocation: zip code & country info
type ConfigClusterLocationType string

const (
	ConfigClusterLocationTypeNotConfigured ConfigClusterLocationType = "NOT_CONFIGURED"
	ConfigClusterLocationTypeCoordinates   ConfigClusterLocationType = "COORDINATES"
	ConfigClusterLocationTypeGeolocation   ConfigClusterLocationType = "GEOLOCATION"
)

func (e ConfigClusterLocationType) ToPointer() *ConfigClusterLocationType {
	return &e
}

func (e *ConfigClusterLocationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_CONFIGURED":
		fallthrough
	case "COORDINATES":
		fallthrough
	case "GEOLOCATION":
		*e = ConfigClusterLocationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConfigClusterLocationType: %v", v)
	}
}
