// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type GooglerpcStatus struct {
	Code    *int           `json:"code,omitempty"`
	Message *string        `json:"message,omitempty"`
	Details []ProtobufAny1 `json:"details,omitempty"`
}

func (o *GooglerpcStatus) GetCode() *int {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GooglerpcStatus) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GooglerpcStatus) GetDetails() []ProtobufAny1 {
	if o == nil {
		return nil
	}
	return o.Details
}
