// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/himanshusahu0001/openapiinternal/utils"
)

type ProtobufAny1 struct {
	AtType               *string                `json:"@type,omitempty"`
	AdditionalProperties map[string]ProtobufAny `additionalProperties:"true" json:"-"`
}

func (p ProtobufAny1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProtobufAny1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ProtobufAny1) GetAtType() *string {
	if o == nil {
		return nil
	}
	return o.AtType
}

func (o *ProtobufAny1) GetAdditionalProperties() map[string]ProtobufAny {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
